language:
  - python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -U pip
  - pip install -e .

script:
  - cd test
  - python vad_test.py
  - python trim_test.py
  - python split_test.py