name: Release to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: pip install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-dynamic-versioning twine
      - name: PyPI Settings
        run: poetry config pypi-token.pypi ${{secrets.PYPI_TOKEN}}
      - name: Build and publish
        run: poetry build --verbose
        # run: poetry publish --build
